name: simpo
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - torch
      - transformers
      - datasets
      - trl
      - accelerate
      - peft
      - huggingface_hub
      - pyyaml
      - wandb
